"""Add accrued_points column to events table

Revision ID: e243385570cd
Revises: 028837656291
Create Date: 2025-02-26 15:38:50.543368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e243385570cd'
down_revision: Union[str, None] = '028837656291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('swipe_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('is_like', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swipe_events_event_id'), 'swipe_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_swipe_events_id'), 'swipe_events', ['id'], unique=False)
    op.create_index(op.f('ix_swipe_events_player_id'), 'swipe_events', ['player_id'], unique=False)
    op.add_column('events', sa.Column('accrued_points', sa.BigInteger, nullable=True))
    op.execute('UPDATE events SET accrued_points = 0 WHERE accrued_points IS NULL')
    op.alter_column('events', 'accrued_points', nullable=False)

    op.add_column('events', sa.Column('level_difficulty', sa.SmallInteger, nullable=True))
    op.execute('UPDATE events SET level_difficulty = 1 WHERE level_difficulty IS NULL')
    op.alter_column('events', 'level_difficulty', nullable=False)

    op.add_column('feedback_events', sa.Column('rating', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_events', 'rating')
    op.drop_column('events', 'level_difficulty')
    op.drop_column('events', 'accrued_points')
    op.drop_index(op.f('ix_swipe_events_player_id'), table_name='swipe_events')
    op.drop_index(op.f('ix_swipe_events_id'), table_name='swipe_events')
    op.drop_index(op.f('ix_swipe_events_event_id'), table_name='swipe_events')
    op.drop_table('swipe_events')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
